apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spike-backend-ingress

spec:
{{/*  ingressClassName: nginx-spike-backend*/}}
  rules:
    - host: spike.vinf.top
      http:
        paths:
          - path: /users
            pathType: Prefix
            backend:
              service:
                name: spike-user-service
                port:
                  number: 8080
