apiVersion: v1
kind: Service
metadata:
  name: spike-nginx
  labels:
    app: spike-nginx
spec:
  ports:
    - port: 80
      name: spike-web
  clusterIP: None
  selector:
    app: spike-nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spike-web
spec:
  serviceName: "spike-nginx"
  replicas: 1
  selector:
    matchLabels:
      app: spike-nginx
  template:
    metadata:
      labels:
        app: spike-nginx
    spec:
      containers:
        - name: spike-nginx
          image: docker.io/library/nginx:latest
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi

