// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.18.1
// source: internal/pb/access/access.proto

package access

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	SpikeId string `protobuf:"bytes,2,opt,name=SpikeId,proto3" json:"SpikeId,omitempty"`
}

func (x *AccessReq) Reset() {
	*x = AccessReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_access_access_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessReq) ProtoMessage() {}

func (x *AccessReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_access_access_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessReq.ProtoReflect.Descriptor instead.
func (*AccessReq) Descriptor() ([]byte, []int) {
	return file_internal_pb_access_access_proto_rawDescGZIP(), []int{0}
}

func (x *AccessReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AccessReq) GetSpikeId() string {
	if x != nil {
		return x.SpikeId
	}
	return ""
}

type AccessRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *AccessRes) Reset() {
	*x = AccessRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_access_access_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRes) ProtoMessage() {}

func (x *AccessRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_access_access_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRes.ProtoReflect.Descriptor instead.
func (*AccessRes) Descriptor() ([]byte, []int) {
	return file_internal_pb_access_access_proto_rawDescGZIP(), []int{1}
}

func (x *AccessRes) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *AccessRes) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_internal_pb_access_access_proto protoreflect.FileDescriptor

var file_internal_pb_access_access_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x61, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x2f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x3d, 0x0a, 0x09, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x53, 0x70, 0x69, 0x6b, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x53, 0x70, 0x69, 0x6b, 0x65, 0x49, 0x64, 0x22, 0x3b, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x32, 0x40, 0x0a, 0x06, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12,
	0x36, 0x0a, 0x0c, 0x49, 0x73, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x12,
	0x11, 0x2e, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52,
	0x65, 0x71, 0x1a, 0x11, 0x2e, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x2e, 0x41, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x16, 0x5a, 0x14, 0x2e, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_pb_access_access_proto_rawDescOnce sync.Once
	file_internal_pb_access_access_proto_rawDescData = file_internal_pb_access_access_proto_rawDesc
)

func file_internal_pb_access_access_proto_rawDescGZIP() []byte {
	file_internal_pb_access_access_proto_rawDescOnce.Do(func() {
		file_internal_pb_access_access_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_pb_access_access_proto_rawDescData)
	})
	return file_internal_pb_access_access_proto_rawDescData
}

var file_internal_pb_access_access_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_pb_access_access_proto_goTypes = []interface{}{
	(*AccessReq)(nil), // 0: access.AccessReq
	(*AccessRes)(nil), // 1: access.AccessRes
}
var file_internal_pb_access_access_proto_depIdxs = []int32{
	0, // 0: access.Access.IsAccessible:input_type -> access.AccessReq
	1, // 1: access.Access.IsAccessible:output_type -> access.AccessRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_pb_access_access_proto_init() }
func file_internal_pb_access_access_proto_init() {
	if File_internal_pb_access_access_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_pb_access_access_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_access_access_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_pb_access_access_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pb_access_access_proto_goTypes,
		DependencyIndexes: file_internal_pb_access_access_proto_depIdxs,
		MessageInfos:      file_internal_pb_access_access_proto_msgTypes,
	}.Build()
	File_internal_pb_access_access_proto = out.File
	file_internal_pb_access_access_proto_rawDesc = nil
	file_internal_pb_access_access_proto_goTypes = nil
	file_internal_pb_access_access_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AccessClient is the client API for Access service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccessClient interface {
	IsAccessible(ctx context.Context, in *AccessReq, opts ...grpc.CallOption) (*AccessRes, error)
}

type accessClient struct {
	cc grpc.ClientConnInterface
}

func NewAccessClient(cc grpc.ClientConnInterface) AccessClient {
	return &accessClient{cc}
}

func (c *accessClient) IsAccessible(ctx context.Context, in *AccessReq, opts ...grpc.CallOption) (*AccessRes, error) {
	out := new(AccessRes)
	err := c.cc.Invoke(ctx, "/access.Access/IsAccessible", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccessServer is the server API for Access service.
type AccessServer interface {
	IsAccessible(context.Context, *AccessReq) (*AccessRes, error)
}

// UnimplementedAccessServer can be embedded to have forward compatible implementations.
type UnimplementedAccessServer struct {
}

func (*UnimplementedAccessServer) IsAccessible(context.Context, *AccessReq) (*AccessRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsAccessible not implemented")
}

func RegisterAccessServer(s *grpc.Server, srv AccessServer) {
	s.RegisterService(&_Access_serviceDesc, srv)
}

func _Access_IsAccessible_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServer).IsAccessible(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/access.Access/IsAccessible",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServer).IsAccessible(ctx, req.(*AccessReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Access_serviceDesc = grpc.ServiceDesc{
	ServiceName: "access.Access",
	HandlerType: (*AccessServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsAccessible",
			Handler:    _Access_IsAccessible_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/pb/access/access.proto",
}
